spring:
  application.name: little-writer-api
  config:
    import:
      - auth.yml
      - storage.yml
      - ai.yml

server:
  tomcat:
    mbeanregistry:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: little-writer-api

logging:
  file:
    name: app.log
---

spring.config.activate.on-profile: test-in-memory
logging:
  level:
    root: INFO

---
spring.config.activate.on-profile: test-local
logging:
  level:
    root: INFO

---
spring.config.activate.on-profile: test-local
logging:
  level:
    root: INFO

---
spring.config.activate.on-profile: prod
logging:
  file:
    name: prod.log
  level:
    root: WARN