###
POST localhost:8080/api/v1/book/progress/init
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJsaXR0bGUtd3JpdGVyIiwibWVtYmVyTm8iOjcsInJvbGUiOiJNRU1CRVIifQ.F95RCFuIdWfGfKqgcHcMPu14sLnIUfriXhEJbYQN4baBQwaPfED7J4QrofKQa-6Qx4YRRG0Hb4HJ8ccX9HevWG3Bgh2aEZWgwSnW0lHoEHhcSt8O9kPs1RYH1tR9zpqFj6UzLkHPUTKC6FTMVAcXGmqw2u96RBq1qRugTW3rn7w4Q1MRH-hTyTmYL8RZDRDlCjVnV_Ox3v-7rRZPYoCa9TzLVdHqKE5ouTVhAaeXMJoE9U17KXssij9eAX0ddrPsTeFPB-62TnwPa26Fu1GxeHwwNI0TEg7n4Yl8SB7o2wwHuE6n7fM7i6qnB488q1Gv2ygyH9qb5cRlqt4UxCFJrw

{
  "backgroundInfo" : "바다",
  "characterId" : 35,
  "userInput" : "바다를 향해 떠남"
}

###
POST localhost:8080/api/v1/book/progress/7d208d7f00e74acd8012610d5ffa456a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJsaXR0bGUtd3JpdGVyIiwibWVtYmVyTm8iOjcsInJvbGUiOiJNRU1CRVIifQ.F95RCFuIdWfGfKqgcHcMPu14sLnIUfriXhEJbYQN4baBQwaPfED7J4QrofKQa-6Qx4YRRG0Hb4HJ8ccX9HevWG3Bgh2aEZWgwSnW0lHoEHhcSt8O9kPs1RYH1tR9zpqFj6UzLkHPUTKC6FTMVAcXGmqw2u96RBq1qRugTW3rn7w4Q1MRH-hTyTmYL8RZDRDlCjVnV_Ox3v-7rRZPYoCa9TzLVdHqKE5ouTVhAaeXMJoE9U17KXssij9eAX0ddrPsTeFPB-62TnwPa26Fu1GxeHwwNI0TEg7n4Yl8SB7o2wwHuE6n7fM7i6qnB488q1Gv2ygyH9qb5cRlqt4UxCFJrw

{
  "userInput" : "잠을 잠"
}

###
GET localhost:8080/api/v1/book/progress/022d85f48a7d4a878073866f608939c2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJsaXR0bGUtd3JpdGVyIiwibWVtYmVyTm8iOjcsInJvbGUiOiJNRU1CRVIifQ.F95RCFuIdWfGfKqgcHcMPu14sLnIUfriXhEJbYQN4baBQwaPfED7J4QrofKQa-6Qx4YRRG0Hb4HJ8ccX9HevWG3Bgh2aEZWgwSnW0lHoEHhcSt8O9kPs1RYH1tR9zpqFj6UzLkHPUTKC6FTMVAcXGmqw2u96RBq1qRugTW3rn7w4Q1MRH-hTyTmYL8RZDRDlCjVnV_Ox3v-7rRZPYoCa9TzLVdHqKE5ouTVhAaeXMJoE9U17KXssij9eAX0ddrPsTeFPB-62TnwPa26Fu1GxeHwwNI0TEg7n4Yl8SB7o2wwHuE6n7fM7i6qnB488q1Gv2ygyH9qb5cRlqt4UxCFJrw

###
POST localhost:8080/api/v1/book/progress/aa0a3e9e8cfa45fd8a093571ee47598b/complete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJsaXR0bGUtd3JpdGVyIiwibWVtYmVyTm8iOjcsInJvbGUiOiJNRU1CRVIifQ.F95RCFuIdWfGfKqgcHcMPu14sLnIUfriXhEJbYQN4baBQwaPfED7J4QrofKQa-6Qx4YRRG0Hb4HJ8ccX9HevWG3Bgh2aEZWgwSnW0lHoEHhcSt8O9kPs1RYH1tR9zpqFj6UzLkHPUTKC6FTMVAcXGmqw2u96RBq1qRugTW3rn7w4Q1MRH-hTyTmYL8RZDRDlCjVnV_Ox3v-7rRZPYoCa9TzLVdHqKE5ouTVhAaeXMJoE9U17KXssij9eAX0ddrPsTeFPB-62TnwPa26Fu1GxeHwwNI0TEg7n4Yl8SB7o2wwHuE6n7fM7i6qnB488q1Gv2ygyH9qb5cRlqt4UxCFJrw

{
  "title": "타이틀입니다",
  "author": "필명입니다"
}